FROM eclipse-temurin:25-jdk-jammy
WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw -q -DskipTests package

EXPOSE 8080
CMD ["java", "-jar", "target/hrms-0.0.1-SNAPSHOT.jar"]
